config/routes.rb
Rails.application.routes.draw do

  resources :feeds
  resources :contacts
  root to: 'pages#home'
  get '/salut(/:name)', to: 'pages#salut', as:'salut'

  resources :posts
  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if
  Rails.env.development?
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path, notice:"Blog crée ! "
    else
      render :new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit

  end

  def update
    @blog.update(blog_params)
    redirect_to blog_path
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"Blog supprimé"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/confirm.html.erb
<h3>Voulez vous vraiment faire ça ?</h3>


<%= form_with(model: @blog, local: true ,url: confirm_blogs_path ) do |form| %>


<%= form.hidden_field :title %>

  <%= form.hidden_field :content %>

  <p>tilre:<%= @blog.title %></p>

  <p>Content:<%= @blog.content %></p>
  
  <%= form.submit  "confirmer" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editer un blog</h1>


<%= form_for @blog do |f| %>

    <div>

      <label>Titre du blog</label>

      <%= f.text_field :title %>
    </div><br>

    <div>

      <label>Contenu du blog</label>

      <%= f.text_field :content %>
    </div><br>

    <div>
      <button type="submit">Modifier le blog</button>
    </div>

<% end %>

app/views/blogs/index.html.erb
<h1>Liste des blogs</h1>

<% @blogs.each do |blog| %>

  <h2><%= blog.title %></h2>

  <h2><%= blog.content %></h2>

  <%= link_to 'Vérifiez les détails', blog_path(blog.id) %>

  <a href="<%= blog_path(blog.id) %>"> lire la suite  </a>
  <a href="<%= edit_blog_path(blog.id) %>">Editer</a>
  <a href="<%= blog_path(blog.id) %>" data-confirm="etes vous sur ?" data-method="DELETE">Supprimer</a>

<% end %>

<br><br>

<a href="<%= new_blog_path %>">Creer un blog </a>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>1 erreur(es) s'est produite </h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %><br>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div><br>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div><br>
  <%= form.submit %>
<% end %>

<!-- <form action="/blogs" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="qbu8RFLhyCuAElg1qr7MLYDEdiEINJdEe1JLQFLr7kyWPFiHCEZKszOrvwON33s9CqGz7njGpBasOzrpYkb8/w==">
  <div class="blog_title">
    <label for="blog_title">Le titre</label>
    <input type="text" name="blog[title]">
  </div>
  <div class="blog_content">
    <label for="blog_content">Content</label>
    <input type="text" name="blog[content]">
  </div>
  <input type="submit" name="commit" value="Create Blog" data-disable-with="Create Blog">
</form> -->

app/views/blogs/show.html.erb
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Remove favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Favorite', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h1>Details du blogs</h1>

<h2><%= @blog.title %></h2>

<h2><%= @blog.content %></h2>